### ISSUE TITLE
Diseñar el diagrama de espina de pescado (Realizarlo con una mejor calidad)

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_ln_ppi2020#2]

**Comment by Aristi1452** [comment]
John Faber, al intentar poner la imagen de diagrama de espina de pescado a traves de un link, la imagen sale cortada, e intentando con otros medios, se sigue cortando

**Comment by JohnFlorez25** [comment]
@Aristi1452 Listo ahí les deje la opciónde subefotos.com que es fácil de implementar y rápida
