### ISSUE TITLE
construir tablero de vision del producto

### ISSUE THREAD

**Issue by santiago923** [JohnFlorez25/equipo4_ln_ppi2020#4]

**Comment by santiago923** [comment]
john, sin querer archive una issues sin querer :c

**Comment by JohnFlorez25** [comment]
@santiago923 , listo ya lo ubiqué en progreso

**Comment by JohnFlorez25** [comment]
@santiago923 , te recomiendo para el tablero que mejor lo hagas con etiquetas HTML así no queda tan pixelado... o realizar una mejor captura si lo quieres agregar como una foto
